### ISSUE TITLE
Terraform State that includes a terraform workspace

### ISSUE THREAD

**Issue by Jamie-BitFlight** [caltechads/deployfish#10]
Hi,
when using a terraform workspace, it creates a folder in the bucket called "env:"
and because of the colons it breaks the validation regex.

Invalid bucket name 
```
"tf-state-mlp-cluster/env:/Default/outputs": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"
```

the yml file starts like this:
```yaml
terraform:
  statefile: 's3://tf-state-mlp-cluster/env:/Default/outputs/state.tfstate'
```

**Comment by cmalek** [comment]
This should be fixed in version 0.18.1.  Thanks for the report!

Chris
