### ISSUE TITLE
Log Driver

### ISSUE THREAD

**Issue by rv-acabrera** [caltechads/deployfish#3]
First off, thanks for creating this project! I was wondering if there is a way to change the log driver from fluentd to awslogs. Would be great to have log driver be a yaml option and the ability to specify the log group name.

**Comment by cmalek** [comment]
Great to see that someone is using it besides us!

Thanks, that's a great suggestion.  We'll work on that.  

Chris

**Comment by glennbach** [comment]
I've updated master with this change. We haven't tried it with awslogs, but it works with fluentd. Please let us know if you have any issues. You can see the docs at [http://deployfish.readthedocs.io/en/latest/yaml.html#logging](url).
