### ISSUE TITLE
Suggestion: Making deployfish more friendly for use as a library

### ISSUE THREAD

**Issue by afosterw** [caltechads/deployfish#33]
I love this library but it is very much geared for use as an independent CLI tool. I've been integrating into an existing CLI tool I already have and have had to hack my way around to get it to work.

Specifically if I could pass boto sessions and config dicts into the underlying classes it would make things much easier to integrate. I'd be happy to provide pull requests if you are amenable.

Thanks and great work on this super useful tool!
-Areth

**Comment by cmalek** [comment]
That sounds great Areth.  We will be happy to review any pull request you want to provide.

Chris

On Nov 21, 2018, at 11:16 AM, Areth Foster-Webster <notifications@github.com<mailto:notifications@github.com>> wrote:


I love this library but it is very much geared for use as an independent CLI tool. I've been integrating into an existing CLI tool I already have and have had to hack my way around to get it to work.

Specifically if I could pass boto sessions and config dicts into the underlying classes it would make things much easier to integrate. I'd be happy to provide pull requests if you are amenable.

Thanks and great work on this super useful tool!
-Areth
