### ISSUE TITLE
secrets support for ecs task definition.

### ISSUE THREAD

**Issue by chrisLeeTW** [caltechads/deployfish#35]
AWS recently launch the native secrets support for ecs with ec2 ssm parameter store. (https://docs.aws.amazon.com/en_us/AmazonECS/latest/developerguide/specifying-sensitive-data.html)

Do have any plan to support it ? If it not currently, I'd like to contribute it ! :)

**Comment by cmalek** [comment]
We don't currently have plans to support that, but we would be more than happy to review a pull request!

**Comment by caltechads** [comment]
We've just added this feature. Keep in mind your roles might need to be adjusted. For example, for a task, the execution_role will need to be able read the parameter store data.
