### ISSUE TITLE
Autoscaling Not Working

### ISSUE THREAD

**Issue by THEStephenStanton** [caltechads/deployfish#38]
https://github.com/caltechads/deployfish/blob/57c23bc7b4a267b3bc4fcf1c6288e2d71d89afbd/deployfish/aws/test/test_ECSServiceCPUAlarm.py#L78

In the line above, it seems to be causing Cloudwatch's alarm to never work. 

So what exactly happens. When creating the autoscaling policy using deployfish, it posts the json to aws just fine; but the state of the alarm never changes from INSUFFICIENT_DATA. If you go in the aws console and select that alarm and then just hit save on it, state of the alarm will go to OK. 

The reason seems to be because "Unit" gets posted to aws which is no longer a valid field

**Comment by cmalek** [comment]
Egads, not good.  Thanks for pointing this out.  I'll have a fix out shortly.

Chris

**Comment by cmalek** [comment]
Ah, it's not that the 'Unit' field itself is invalid, it's that the value i'm passing is wrong for cpu-- it should be 'Percent'.  I'll fix.

**Comment by THEStephenStanton** [comment]
Ah ok, gotcha. Good find then.

**Comment by cmalek** [comment]
This is fixed.  New alarms should be created correctly, and If you do `deploy update <service_name>`, that will fix your existing service alarms.

This is on PyPI as deployfish-0.28.1.
