### ISSUE TITLE
Maximum Percent / Minimum Healthy Percent

### ISSUE THREAD

**Issue by rv-cohall** [caltechads/deployfish#4]
Do you think it would be possible to add the ability to specify the maximum percent and minimum healthy percent when defining a service? Right now it defaults the minimum healthy percent to 0 which means that during deployments ECS can kill all running tasks before starting new ones.

**Comment by cmalek** [comment]
Yes, that's definitely something we forgot, and it has actually bitten me already.  We'll fix.
