### ISSUE TITLE
Fargate Support

### ISSUE THREAD

**Issue by rv-cohall** [caltechads/deployfish#5]
Is there any plan to add support for creating Fargate services?

**Comment by caltechads** [comment]
That's a very good question. We hadn't discussed it yet, since we aren't using Fargate at this time. It does seem like a good idea, though. We'll put this on our roadmap, though I can't make any timing promises at this point. We'd love any suggestions you have to offer on how best to support it.

**Comment by rv-cohall** [comment]
I started working on a pull request that I'll submit early next week that I think will work.

**Comment by caltechads** [comment]
Excellent. Try to expedite the merge.

**Comment by glennbach** [comment]
What I meant to say was that I will try to expedite the merge. 

Glenn
