### ISSUE TITLE
deploy: command not found

### ISSUE THREAD

**Issue by Uri-Katsir** [caltechads/deployfish#8]
Hello,

I installed the product on Amazon Linux using "pip install deployfish" and configured the basic yml file.
When I run "deploy create hello-world-test," I received an error message:  bash: deploy: command not found

Thank you

Uri

**Comment by caltechads** [comment]
Hi Uri,

Sorry about that. Which tutorial gave you the error?

Glenn

**Comment by cmalek** [comment]
And could you do this for us:  

```
pip show -f deployfish
```

**Comment by Uri-Katsir** [comment]
Hi Glenn,
I ran "deploy --help" and received "bash: deploy: command not found"

The output of pip show -f deployfish is below:
Name: deployfish
Version: 0.18.0
Summary: AWS ECS related deployment tools
Home-page: https://github.com/caltechads/deployfish
Author: Caltech IMSS ADS
Author-email: imss-ads-staff@caltech.edu
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: PyYAML, click, tzlocal, boto3
Files:
  ../../../bin/deploy
  ../../../bin/dpy
  deployfish-0.18.0.dist-info/DESCRIPTION.rst
  deployfish-0.18.0.dist-info/INSTALLER
  deployfish-0.18.0.dist-info/METADATA
  deployfish-0.18.0.dist-info/RECORD
  deployfish-0.18.0.dist-info/WHEEL
  deployfish-0.18.0.dist-info/entry_points.txt
  deployfish-0.18.0.dist-info/metadata.json
  deployfish-0.18.0.dist-info/top_level.txt
  deployfish/__init__.py
  deployfish/__init__.pyc
  deployfish/aws/__init__.py
  deployfish/aws/__init__.pyc
  deployfish/aws/appscaling.py
  deployfish/aws/appscaling.pyc
  deployfish/aws/asg.py
  deployfish/aws/asg.pyc
  deployfish/aws/cloudwatch.py
  deployfish/aws/cloudwatch.pyc
  deployfish/aws/ecs.py
  deployfish/aws/ecs.pyc
  deployfish/aws/s3.py
  deployfish/aws/s3.pyc
  deployfish/aws/systems_manager.py
  deployfish/aws/systems_manager.pyc
  deployfish/cli.py
  deployfish/cli.pyc
  deployfish/config.py
  deployfish/config.pyc
  deployfish/dbcli.py
  deployfish/dbcli.pyc
  deployfish/dplycli.py
  deployfish/dplycli.pyc
  deployfish/mysql.py
  deployfish/mysql.pyc
  deployfish/terraform.py
  deployfish/terraform.pyc
  deployfish/test/__init__.py
  deployfish/test/__init__.pyc
  deployfish/test/test_Config.py
  deployfish/test/test_Config.pyc
  deployfish/test/test_Terraform.py
  deployfish/test/test_Terraform.pyc

**Comment by cmalek** [comment]
Looks like pip at least thinks it installed `deploy` and its alias, `dpy`.   

If you installed it as root, it those binaries should be in `/usr/bin`.   Can you look in that directory to see if `deploy` and `dpy` exist there?  Also, do:

`echo $PATH` 

for us.

**Comment by Uri-Katsir** [comment]
All good now

Thank you
